export const API_URL = 'https://norma.nomoreparties.space/api';
// ingredients actions
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INCREMENT_AMOUNT = 'INCREMENT_AMOUNT';
export const DECREMENT_AMOUNT = 'DECREMENT_AMOUNT';
// burger actions
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
// order actions
export const POST_ORDER = 'POST_ORDER';
// authentication actions
export const ACTION_TYPE_LOGIN = 'ACTION_TYPE_LOGIN';
export const ACTION_TYPE_LOGOUT = 'ACTION_TYPE_LOGOUT';
// export const ACTION_TYPE_GET_USER = 'ACTION_TYPE_GET_USER';
// export const ACTION_TYPE_UPDATE_USER = 'ACTION_TYPE_UPDATE_USER';
export const ACTION_TYPE_SET_USER_DATA = 'ACTION_TYPE_SET_USER_DATA';
export const ACTION_TYPE_SET_USER_LOGGED_IN = 'ACTION_TYPE_SET_USER_LOGGED_IN';
export const ACTION_TYPE_SET_PASSWORD_RESET_CODE_SENT = 'ACTION_TYPE_SET_PASSWORD_RESET_CODE_SENT'
export const ACTION_TYPE_SET_PASSWORD_RESET = 'ACTION_TYPE_SET_PASSWORD_RESET'

// other
export const ACCESS_TOKEN_EXPIRATION_TIME_IN_MIN = 15;